### ISSUE TITLE
Add a GitHub Actions .yml file

### ISSUE THREAD

**Issue by calcmogul** [wpilibsuite/vendor-template#4]
This should build the vendor dependency for all platforms and publish to a maven server when building master. This would help address vendors only building for platforms they have access to instead of all the platforms WPILib supports.

Here's one that may work as a starting point: https://github.com/PhotonVision/photonlib/blob/master/.github/workflows/main.yml

Getting the CI to pass when there's nothing for the vendor-template to upload to may be tricky.

**Comment by calcmogul** [comment]
Another option is the .yml and check.py in https://github.com/wpilibsuite/vendor-json-repo/.

**Comment by rzblue** [comment]
Added in #11
