### ISSUE TITLE
Make Public Template

### ISSUE THREAD

**Issue by GeraldTM** [wpilibsuite/vendor-template#9]
Could you make this a public template in options, for ease of use?

**Comment by ThadHouse** [comment]
What do you mean? This repo is already public, anyone can make a copy of it for their own project.

**Comment by GeraldTM** [comment]
the option "Template Repository" in settings adds a button that says "Use This Template", which automaticly copys the repo, and adds a note saying "generated from _user/repository_". It is nice because people don't get the "_ # of commits behind main", that they do from forking, and it still gives you credit

**Comment by GeraldTM** [comment]
you can see an example in [my fork](https://github.com/GeraldTM/vendor-template)

**Comment by ThadHouse** [comment]
Oh thats cool, I didn't know that existed. I just enabled it. Thanks!
